export { default as Home } from './Home'
export {default as UserForm} from './UserForm'
export {default as Activities} from './Activities'
export {default as MyRoutines} from './MyRoutines'
export {default as Routines} from './Routines'
