export { default as Home } from './home'
export {default as UserForm} from './userform'
export {default as Activities} from './Activities'
export {default as MyRoutines} from './myRoutines'
export {default as Routines} from './Routines'
